import { config } from 'dotenv';
config({ path: `.env.${process.env.NODE_ENV || 'development'}.local` });

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  PORT,
  ORIGIN,
  LOG_DIR,
  NODE_ENV,
  LOG_FORMAT,
  AWS_REGION,
  AWS_ACCESS_KEY,
  AWS_SECRET_ACCESS_KEY,
  AWS_COGNITO_USER_POOL_ID,
  FRONTEND_APPLICATION_URL,
  STRIPE_SECRET_KEY,
  STRIPE_CHECKOUT_CALLBACK_URL,
  STRIPE_CHECKOUT_COMPLETE_BILLING_SIGNING_SECRET,
  STRIPE_PRODUCT_ID_FOR_MONTHLY_SUBSCRIPTION,
  STRIPE_PRODUCT_ID_FOR_YEARLY_SUBSCRIPTION,
} = process.env;
